"""Phase 4 temporal smoothing (spec §3).

Three deterministic operators applied in fixed order:

1. ``_merge_same_label`` — collapse adjacent same-phase segments (spec §3.2).
2. ``_merge_short`` — absorb short segments into highest-confidence neighbor (§3.3).
3. ``_viterbi_relabel`` — DP relabel with forbidden-transition penalty (§3.4),
   skipped when ``viterbi_enabled=False`` or when the segment count is < 2.

Public API::

    apply_smoothing(segments, *, config, labelset) -> SmoothingResult

Internal helpers (``_merge_same_label`` / ``_merge_short`` / ``_viterbi_relabel``
/ ``_recompute_confidence``) are exposed for unit-test assertions on the
operator semantics; they are not part of the public stable surface.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Literal

from mimicanno.config import SmootherConfig
from mimicanno.schema import SmoothingSummary, SubtaskSegment

SmoothingOp = Literal["merge_same_label", "merge_short", "viterbi_relabel"]
_RESERVED_PHASES: frozenset[str] = frozenset({"unlabeled", "unknown"})


@dataclass(slots=True)
class SmoothingResult:
    """Returned by :func:`apply_smoothing` (spec §1.2)."""

    segments: list[SubtaskSegment]
    summary: SmoothingSummary
    ops_log: list[tuple[SmoothingOp, list[str]]] = field(default_factory=list)
    """Ordered log of ops applied; each entry is
    ``(op_name, list_of_segment_ids_post_op)``."""


def _recompute_confidence(seg: SubtaskSegment) -> SubtaskSegment:
    """Re-derive ``boundary_confidence`` and ``overall_confidence`` per spec §3.5.

    boundary_confidence = min(start_boundary.score, end_boundary.score)   [parent §6.1]
    overall_confidence  = 0.0                              if phase ∈ {unlabeled, unknown}
                        = boundary_confidence              if vlm_confidence is None
                        = sqrt(boundary * vlm)             otherwise        [parent §6.4]

    Returns a new segment dataclass; the input is not mutated.
    """
    bc = min(seg.start_boundary.score, seg.end_boundary.score)
    if seg.phase in _RESERVED_PHASES:
        oc = 0.0
    elif seg.vlm_confidence is None:
        oc = bc
    else:
        oc = math.sqrt(bc * seg.vlm_confidence)
    return replace(seg, boundary_confidence=bc, overall_confidence=oc)


def _dedup_consecutive(ops: list[str]) -> list[str]:
    """Collapse consecutive duplicate entries (spec §3.2 / §4.1)."""
    out: list[str] = []
    for op in ops:
        if not out or out[-1] != op:
            out.append(op)
    return out


def _renumber_segment_ids(segments: list[SubtaskSegment]) -> list[SubtaskSegment]:
    """Spec §4.2: ``segment_id = f'{episode_id}__seg{idx:04d}'``."""
    return [
        replace(s, segment_id=f"{s.episode_id}__seg{idx:04d}")
        for idx, s in enumerate(segments)
    ]


def _weighted_mean_vlm(left: SubtaskSegment, right: SubtaskSegment) -> float | None:
    """Duration-weighted mean of two segments' ``vlm_confidence``.

    None handling per spec §3.2: both None → None; exactly one None → the
    non-None value alone.
    """
    if left.vlm_confidence is None and right.vlm_confidence is None:
        return None
    if left.vlm_confidence is None:
        return right.vlm_confidence
    if right.vlm_confidence is None:
        return left.vlm_confidence
    d_l = left.end_time - left.start_time
    d_r = right.end_time - right.start_time
    total = d_l + d_r
    if total <= 0:
        return (left.vlm_confidence + right.vlm_confidence) / 2
    return (left.vlm_confidence * d_l + right.vlm_confidence * d_r) / total


def _merge_pair_same_label(
    left: SubtaskSegment, right: SubtaskSegment,
) -> SubtaskSegment:
    """Merge two adjacent same-phase segments per spec §3.2 field rules."""
    higher = left if left.overall_confidence >= right.overall_confidence else right

    if left.label_version != right.label_version:
        raise AssertionError(
            f"label_version differs across run: "
            f"{left.label_version} vs {right.label_version}",
        )

    merged = SubtaskSegment(
        segment_id="",  # regenerated by caller
        episode_id=left.episode_id,
        start_frame=left.start_frame, end_frame=right.end_frame,
        start_time=left.start_time, end_time=right.end_time,
        phase=higher.phase,
        verb=higher.verb, object=higher.object, target=higher.target,
        failure_flags=sorted(set(left.failure_flags) | set(right.failure_flags)),
        label_source=higher.label_source,
        object_state_unavailable=(
            left.object_state_unavailable or right.object_state_unavailable
        ),
        object_track_ids=sorted(
            set(left.object_track_ids) | set(right.object_track_ids),
        ),
        label_version=left.label_version,
        start_boundary=left.start_boundary,
        end_boundary=right.end_boundary,
        boundary_confidence=0.0,    # _recompute_confidence fills below
        vlm_confidence=_weighted_mean_vlm(left, right),
        overall_confidence=0.0,     # _recompute_confidence fills below
        evidence=higher.evidence,
        reviewed=False,
        reviewer_id=None,
        smoothing_ops=_dedup_consecutive(
            list(left.smoothing_ops)
            + list(right.smoothing_ops)
            + ["merge_same_label"],
        ),
    )
    return _recompute_confidence(merged)


def _do_one_merge_round(
    segments: list[SubtaskSegment],
) -> tuple[list[SubtaskSegment], int]:
    """One left-to-right merge pass over adjacent same-phase pairs.

    Returns ``(new_list, collapse_count_in_this_round)``.
    """
    if len(segments) <= 1:
        return list(segments), 0
    out: list[SubtaskSegment] = []
    collapses = 0
    i = 0
    while i < len(segments):
        if i + 1 < len(segments) and segments[i].phase == segments[i + 1].phase:
            out.append(_merge_pair_same_label(segments[i], segments[i + 1]))
            collapses += 1
            i += 2
        else:
            out.append(segments[i])
            i += 1
    return out, collapses


def _merge_same_label(
    segments: list[SubtaskSegment],
) -> tuple[list[SubtaskSegment], int, int]:
    """Op 1 (spec §3.2). Returns ``(segments, rounds, total_collapses)``.

    Iterates rounds until a round performs no collapse. ``rounds`` counts
    productive rounds only (the terminating no-op round is not counted).
    """
    rounds = 0
    total_collapses = 0
    current = list(segments)
    while True:
        out, collapses = _do_one_merge_round(current)
        if collapses == 0:
            break
        rounds += 1
        total_collapses += collapses
        current = out
    return _renumber_segment_ids(current), rounds, total_collapses


def apply_smoothing(
    segments: list[SubtaskSegment],
    *,
    config: SmootherConfig,
    labelset: list[str],
) -> SmoothingResult:
    """Phase 4 smoothing pipeline (spec §3). Stub — Tasks 8-10 fill in Ops 2-3."""
    raise NotImplementedError("Tasks 8-10 implement Ops 2-3 and the orchestrator.")
