"""Phase 4 temporal smoothing (spec §3).

Three deterministic operators applied in fixed order:

1. ``_merge_same_label`` — collapse adjacent same-phase segments (spec §3.2).
2. ``_merge_short`` — absorb short segments into highest-confidence neighbor (§3.3).
3. ``_viterbi_relabel`` — DP relabel with forbidden-transition penalty (§3.4),
   skipped when ``viterbi_enabled=False`` or when the segment count is < 2.

Public API::

    apply_smoothing(segments, *, config, labelset) -> SmoothingResult

Internal helpers (``_merge_same_label`` / ``_merge_short`` / ``_viterbi_relabel``
/ ``_recompute_confidence``) are exposed for unit-test assertions on the
operator semantics; they are not part of the public stable surface.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Literal

from mimicanno.config import SmootherConfig
from mimicanno.schema import SmoothingSummary, SubtaskSegment

SmoothingOp = Literal["merge_same_label", "merge_short", "viterbi_relabel"]
_RESERVED_PHASES: frozenset[str] = frozenset({"unlabeled", "unknown"})


@dataclass(slots=True)
class SmoothingResult:
    """Returned by :func:`apply_smoothing` (spec §1.2)."""

    segments: list[SubtaskSegment]
    summary: SmoothingSummary
    ops_log: list[tuple[SmoothingOp, list[str]]] = field(default_factory=list)
    """Ordered log of ops applied; each entry is
    ``(op_name, list_of_segment_ids_post_op)``."""


def _recompute_confidence(seg: SubtaskSegment) -> SubtaskSegment:
    """Re-derive ``boundary_confidence`` and ``overall_confidence`` per spec §3.5.

    boundary_confidence = min(start_boundary.score, end_boundary.score)   [parent §6.1]
    overall_confidence  = 0.0                              if phase ∈ {unlabeled, unknown}
                        = boundary_confidence              if vlm_confidence is None
                        = sqrt(boundary * vlm)             otherwise        [parent §6.4]

    Returns a new segment dataclass; the input is not mutated.
    """
    bc = min(seg.start_boundary.score, seg.end_boundary.score)
    if seg.phase in _RESERVED_PHASES:
        oc = 0.0
    elif seg.vlm_confidence is None:
        oc = bc
    else:
        oc = math.sqrt(bc * seg.vlm_confidence)
    return replace(seg, boundary_confidence=bc, overall_confidence=oc)


def _dedup_consecutive(ops: list[str]) -> list[str]:
    """Collapse consecutive duplicate entries (spec §3.2 / §4.1)."""
    out: list[str] = []
    for op in ops:
        if not out or out[-1] != op:
            out.append(op)
    return out


def _renumber_segment_ids(segments: list[SubtaskSegment]) -> list[SubtaskSegment]:
    """Spec §4.2: ``segment_id = f'{episode_id}__seg{idx:04d}'``."""
    return [
        replace(s, segment_id=f"{s.episode_id}__seg{idx:04d}")
        for idx, s in enumerate(segments)
    ]


def _weighted_mean_vlm(left: SubtaskSegment, right: SubtaskSegment) -> float | None:
    """Duration-weighted mean of two segments' ``vlm_confidence``.

    None handling per spec §3.2: both None → None; exactly one None → the
    non-None value alone.
    """
    if left.vlm_confidence is None and right.vlm_confidence is None:
        return None
    if left.vlm_confidence is None:
        return right.vlm_confidence
    if right.vlm_confidence is None:
        return left.vlm_confidence
    d_l = left.end_time - left.start_time
    d_r = right.end_time - right.start_time
    total = d_l + d_r
    if total <= 0:
        return (left.vlm_confidence + right.vlm_confidence) / 2
    return (left.vlm_confidence * d_l + right.vlm_confidence * d_r) / total


def _merge_pair_same_label(
    left: SubtaskSegment, right: SubtaskSegment,
) -> SubtaskSegment:
    """Merge two adjacent same-phase segments per spec §3.2 field rules."""
    higher = left if left.overall_confidence >= right.overall_confidence else right

    if left.label_version != right.label_version:
        raise AssertionError(
            f"label_version differs across run: "
            f"{left.label_version} vs {right.label_version}",
        )

    merged = SubtaskSegment(
        segment_id="",  # regenerated by caller
        episode_id=left.episode_id,
        start_frame=left.start_frame, end_frame=right.end_frame,
        start_time=left.start_time, end_time=right.end_time,
        phase=higher.phase,
        verb=higher.verb, object=higher.object, target=higher.target,
        failure_flags=sorted(set(left.failure_flags) | set(right.failure_flags)),
        label_source=higher.label_source,
        object_state_unavailable=(
            left.object_state_unavailable or right.object_state_unavailable
        ),
        object_track_ids=sorted(
            set(left.object_track_ids) | set(right.object_track_ids),
        ),
        label_version=left.label_version,
        start_boundary=left.start_boundary,
        end_boundary=right.end_boundary,
        boundary_confidence=0.0,    # _recompute_confidence fills below
        vlm_confidence=_weighted_mean_vlm(left, right),
        overall_confidence=0.0,     # _recompute_confidence fills below
        evidence=higher.evidence,
        reviewed=False,
        reviewer_id=None,
        smoothing_ops=_dedup_consecutive(
            list(left.smoothing_ops)
            + list(right.smoothing_ops)
            + ["merge_same_label"],
        ),
    )
    return _recompute_confidence(merged)


def _do_one_merge_round(
    segments: list[SubtaskSegment],
) -> tuple[list[SubtaskSegment], int]:
    """One left-to-right merge pass over adjacent same-phase pairs.

    Returns ``(new_list, collapse_count_in_this_round)``.
    """
    if len(segments) <= 1:
        return list(segments), 0
    out: list[SubtaskSegment] = []
    collapses = 0
    i = 0
    while i < len(segments):
        if i + 1 < len(segments) and segments[i].phase == segments[i + 1].phase:
            out.append(_merge_pair_same_label(segments[i], segments[i + 1]))
            collapses += 1
            i += 2
        else:
            out.append(segments[i])
            i += 1
    return out, collapses


def _merge_same_label(
    segments: list[SubtaskSegment],
) -> tuple[list[SubtaskSegment], int, int]:
    """Op 1 (spec §3.2). Returns ``(segments, rounds, total_collapses)``.

    Iterates rounds until a round performs no collapse. ``rounds`` counts
    productive rounds only (the terminating no-op round is not counted).
    """
    rounds = 0
    total_collapses = 0
    current = list(segments)
    while True:
        out, collapses = _do_one_merge_round(current)
        if collapses == 0:
            break
        rounds += 1
        total_collapses += collapses
        current = out
    return _renumber_segment_ids(current), rounds, total_collapses


def _absorb(
    into: SubtaskSegment, absorbed: SubtaskSegment, *, on_left: bool,
) -> SubtaskSegment:
    """Merge ``absorbed`` into ``into`` per spec §3.3.

    ``on_left`` = True means ``absorbed`` is to the LEFT of ``into``.
    The surviving segment's phase / verb / object / target / label_source come
    from ``into`` regardless of confidence (spec §3.3 step 4).
    """
    if on_left:
        new_start = absorbed.start_boundary
        new_end = into.end_boundary
        new_start_frame, new_start_time = absorbed.start_frame, absorbed.start_time
        new_end_frame, new_end_time = into.end_frame, into.end_time
    else:
        new_start = into.start_boundary
        new_end = absorbed.end_boundary
        new_start_frame, new_start_time = into.start_frame, into.start_time
        new_end_frame, new_end_time = absorbed.end_frame, absorbed.end_time

    if into.label_version != absorbed.label_version:
        raise AssertionError(
            f"label_version differs across run: "
            f"{into.label_version} vs {absorbed.label_version}",
        )

    merged = SubtaskSegment(
        segment_id="",
        episode_id=into.episode_id,
        start_frame=new_start_frame, end_frame=new_end_frame,
        start_time=new_start_time, end_time=new_end_time,
        # Spec §3.3: surviving (`into`) side wins on label fields
        phase=into.phase, verb=into.verb, object=into.object, target=into.target,
        failure_flags=sorted(set(into.failure_flags) | set(absorbed.failure_flags)),
        label_source=into.label_source,
        object_state_unavailable=(
            into.object_state_unavailable or absorbed.object_state_unavailable
        ),
        object_track_ids=sorted(
            set(into.object_track_ids) | set(absorbed.object_track_ids),
        ),
        label_version=into.label_version,
        start_boundary=new_start, end_boundary=new_end,
        boundary_confidence=0.0,
        vlm_confidence=_weighted_mean_vlm(into, absorbed),
        overall_confidence=0.0,
        evidence=into.evidence,
        reviewed=False, reviewer_id=None,
        smoothing_ops=_dedup_consecutive(
            list(into.smoothing_ops)
            + list(absorbed.smoothing_ops)
            + ["merge_short"],
        ),
    )
    return _recompute_confidence(merged)


def _is_short(seg: SubtaskSegment, *, threshold_sec: float) -> bool:
    return (seg.end_time - seg.start_time) < threshold_sec


def _merge_short(
    segments: list[SubtaskSegment],
    *,
    config: SmootherConfig,
) -> tuple[list[SubtaskSegment], int]:
    """Op 2 (spec §3.3). Returns ``(segments, total_absorbs)``.

    Repeats left-to-right passes until no segment is below
    ``min_segment_duration_sec``. After a merge, the index restarts at
    ``max(i - 1, 0)`` so the survivor is re-evaluated. Tie-break on
    ``overall_confidence`` prefers left; on a tie, prefers the side that
    does NOT induce a forbidden transition with the opposite-side neighbor.
    """
    threshold = config.min_segment_duration_sec
    forbidden = set(config.forbidden_transitions)
    if len(segments) <= 1:
        return list(segments), 0

    current = list(segments)
    total_absorbs = 0
    while True:
        i = 0
        progress_in_pass = False
        while i < len(current):
            seg = current[i]
            if not _is_short(seg, threshold_sec=threshold):
                i += 1
                continue
            has_left = i > 0
            has_right = i + 1 < len(current)
            if not has_left and not has_right:
                # Single short segment with no neighbor: pass-through.
                i += 1
                continue
            if has_left and not has_right:
                merged = _absorb(into=current[i - 1], absorbed=seg, on_left=False)
                current = current[: i - 1] + [merged] + current[i + 1 :]
                total_absorbs += 1
                progress_in_pass = True
                i = max(i - 1, 0)
                continue
            if has_right and not has_left:
                merged = _absorb(into=current[i + 1], absorbed=seg, on_left=True)
                current = current[:i] + [merged] + current[i + 2 :]
                total_absorbs += 1
                progress_in_pass = True
                # i unchanged — survivor is now at index i, may itself be short
                continue
            # Both neighbors exist
            left = current[i - 1]
            right = current[i + 1]
            if left.overall_confidence > right.overall_confidence:
                pick_left = True
            elif right.overall_confidence > left.overall_confidence:
                pick_left = False
            else:
                # Tie: prefer the side that does NOT create a forbidden
                # transition with the opposite-side neighbor.
                # If absorb-left → merged-left would sit next to `right`;
                # check (left.phase, right.phase) ∈ forbidden.
                # If absorb-right → merged-right would sit next to `left`;
                # check (left.phase, right.phase) ∈ forbidden.
                # Both options yield the same adjacent pair; in that case
                # the "forbidden-avoidance" criterion is symmetric, so
                # default to left preference.
                pair_after_absorb_left = (left.phase, right.phase)
                pair_after_absorb_right = (left.phase, right.phase)
                left_creates = pair_after_absorb_left in forbidden
                right_creates = pair_after_absorb_right in forbidden
                if left_creates and not right_creates:
                    pick_left = False
                elif right_creates and not left_creates:
                    pick_left = True
                else:
                    pick_left = True   # default left preference
            if pick_left:
                merged = _absorb(into=left, absorbed=seg, on_left=False)
                current = current[: i - 1] + [merged] + current[i + 1 :]
                i = max(i - 1, 0)
            else:
                merged = _absorb(into=right, absorbed=seg, on_left=True)
                current = current[:i] + [merged] + current[i + 2 :]
                # i unchanged
            total_absorbs += 1
            progress_in_pass = True
        if not progress_in_pass:
            break
    return _renumber_segment_ids(current), total_absorbs


def apply_smoothing(
    segments: list[SubtaskSegment],
    *,
    config: SmootherConfig,
    labelset: list[str],
) -> SmoothingResult:
    """Phase 4 smoothing pipeline (spec §3). Stub — Tasks 9-10 fill in Op 3."""
    raise NotImplementedError("Tasks 9-10 implement Op 3 and the orchestrator.")
